sudo: required

services:
    - docker

before_install: 
    - docker build -t davisochieng4/docker-react -f Dockerfile.dev .

script: 
    - docker run davisochieng4/docker-react npm run test -- --coverage 